# Kernel information
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_PAGESIZE := 2048
BOARD_NAME := EU_P653A10V1.0.Y
BOARD_KERNEL_BASE := 0x40080000
BOARD_KERNEL_OFFSET := 0x00000000
BOARD_RAMDISK_OFFSET := 0x03f80000
BOARD_TAGS_OFFSET := 0x0df80000
BOARD_SECOND_OFFSET := 0x00e80000
BOARD_MKBOOTIMG_ARGS := --board $(BOARD_NAME) --base $(BOARD_KERNEL_BASE) --pagesize $(BOARD_KERNEL_PAGESIZE) --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET) --second_offset $(BOARD_SECOND_OFFSET)
TARGET_IS_64_BIT := true
MTK_K64_SUPPORT := yes

# Kernel properties
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_SOURCE := kernel/zte/bladev7plus.selinuxfix
TARGET_KERNEL_CONFIG := ztesh6753_65u_m0_defconfig
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
MTK_APPENDED_DTB_SUPPORT := yes
